version: '4'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: catalog_service
      POSTGRES_USER: catalog_user
      POSTGRES_PASSWORD: pass
    volumes:
      - ./docker:/docker-entrypoint-initdb.d